url: "https://netfizz.im" # the base hostname & protocol for your site

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

gist:
  noscript: true

# Site settings
title: netfizz ltd
description: > # this means to ignore newlines until "baseurl:"
   netfizz ltd - IM based software consultancy
baseurl: #the subpath of your site, e.g. /blog/

twitter_username: netfizz_co_uk
github_username:  netfizz_co_uk 
medium_username:  netfizz_co_uk 
orgname: netfizz_co_uk

contact:
  location: "Isle of Man"
  # phone: "0000.."
  # email: sales@netfizz_co_uk.com

# Commenting
comments:
  provider: disqus

## Disqus
disqus:
  shortname: mergefailure-com

# Pagination 
paginate: 3
paginate_path: "blog/page:num"

## => Build
##############################
#markdown    : kramdown
#highlighter : rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
permalink   : date

exclude:
  - /.github
  - /.git*
  - .*.swp
  - Dockerfile
  - /docker
  - /docs
  - /node_modules
  - /screenshots
  - /svg
  - /test
  - /vendor
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - HOW_TO_RELEASE.md
  - LICENSE
  - Makefile
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json

sass:
    style: compressed
    sass_dir: _sass
